force-app/main/default/objects/Credit_Memo__c/Credit_Memo__c.object-meta.xml
<CustomObject>
    <label>Credit Memo</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Credit Memo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Memos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit_Memo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to customer record</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Memos</relationshipLabel>
    <relationshipName>Credit_Memos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/imageName__c.field-meta.xml
<CustomField>
    <fullName>imageName__c</fullName>
    <label>imageName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credit_Memo__c/fields/note__c.field-meta.xml
<CustomField>
    <fullName>note__c</fullName>
    <defaultValue>$Setup.Setting__c.defaultNotes__c</defaultValue>
    <label>Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Setting__c/fields/imageHardCodeUrl__c.field-meta.xml
<CustomField>
    <fullName>imageHardCodeUrl__c</fullName>
    <defaultValue>&#39;/sfc/servlet.shepherd/version/download/&#39;</defaultValue>
    <label>imageHardCodeUrl</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/downloadPdfController.cls
public class downloadPdfController {
    Id memoId;
    public String imageUrl{get;set;}
    public Credit_Memo__c credit{get;set;}
    public List<String> notes {get;set;}
    public downloadPdfController() {
        setDatas();
    }
    
    public downloadPdfController(ApexPages.StandardController sc) {
        setDatas();
    }
    
    private void setDatas() {
        Id recordId =  Apexpages.currentPage().getParameters().get('id') != null ? Apexpages.currentPage().getParameters().get('id') : 'a002w000003FRgj';
        List<Credit_Memo__c> creditRecordList = [select id, Account__r.name,name, Credit_Expiry_Date__c,
                                       Credit_Memo_Date__c, Exchange_Rate__c,note__c, Amount__c, imageName__c from Credit_Memo__c where id = :recordId limit 1]; 
        if(creditRecordList.isEmpty()) {
            return;
        }
        credit = creditRecordList.get(0);
        System.debug('credit url '+ credit);
        
		notes =	!String.isBlank(credit.note__c) ? credit.note__c.split('\n') : new List<String>();
        List<contentversion> cv = [select id,contentdocumentid , title from contentversion where title = :credit.imageName__c and islatest = true limit 1];
        imageUrl = Setting__c.getOrgDefaults().imageHardCodeUrl__c + cv.get(0).id;
        System.debug('image url '+ imageUrl);
    }
}